### ISSUE TITLE
Parcelport Cleanup

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#1021]
The implementation of the various parcelports currently contains too much code duplication. In addition, the following tickets needs to be fixed in this process:
- [x] refactor parcelport to allow better solutions for the remaining points (This has been completed with ea72168f193ae16bf7b434a831b24e43107c3522)
- [x] #857: hpx::naming::locality leaks parcelport specific information into the public interface
- [x] #840: Create more versatile ibverbs parcelport.
- [x] #839: Refactor ibverbs and shmem parcelport
- [ ] #812: Implement zero-copy serialization for action arguments
- [x] #680: Convert parcel ports into a plugin system
- [x] #152: Parcels received before the early_parcel_sink is registered may cause problems
