### ISSUE TITLE
Thread manager cleanup

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1056]
The thread manager subsystem requires some significant clean up to reduce code replication. This includes:
- [x] #971 - Add affinity data to all schedulers

Also, we have a couple of tickets open which are related:
- [x] #533 - Thread queue/deque internal parameters should be runtime configurable 
- [x] #624 - Update thread deque with thread queue fixes
- [x] ~~#941 - Create a proper user level context switching class for BG/Q~~
- [x] #1053 - Work stealing flawed (commits towards this: 4aaeadf0df7c96f05494e2ab528085b581b5e76b, 57658428c6cc7cd01f5f1a85b2e0101edbc1baee, ea7471af81dc1574cc3910655d4178937b4571a5, 9d1878d4e8c879a926f9bcb0b9010ea6fa4d1674) 
- [x] #1054 - Work stealing always starts with core zero 
- [x] #1055 - Thread allocation uses two memory pools  (commits towards this: d1d2eb853d2949fe759cf0ee9f27129b9eb2a733)
- [x] #1057 - Add performance counters for threading subsystem

**Comment by hkaiser** [comment]
This has been resolved by now
