### ISSUE TITLE
Serialization issues

### ISSUE THREAD

**Issue by AntonBikineev** [STEllAR-GROUP/hpx#1472]
Here is a ticket gathering all serialization issues and additions. It may be extended.

- [x] getting rid of `serialize_sequence` and moving all sequence serialization into `hpx::util::tuple`; see #1780
- [x] assign unique integer ids to typeids on zero node inside `register_worker_action` to avoid long string lookup in `polymorphic_factory` (done in my working copy, should be refined), see #1482, #1600.
- [x] Add support for serializing objects without default constructor (#1690)
- [x] Add testing of all serialization functionality 
- [x] Merge #1470: Removing hpx::util::polymorphic_factory
- [x] Integrate work done on https://github.com/STEllAR-GROUP/hpx/compare/serialization_tuning
- [x] ~~Reconsider const correctness. In particular, it should be possible to have `serialize(output_archive&, T const&)` overloads~~
- [x] ~~Consider removing split macros. They should not be needed given that we do not have to support generic archives, overloading on `[input|output]_archive` should be enough~~

**Comment by aserio** [comment]
Would it be possible to add some tests to this list?

**Comment by sithhell** [comment]
@aserio the serialization is unit tested already, what tests do you miss?

**Comment by AntonBikineev** [comment]
@sithhell I was thinking it would be nice to add test case for zerocopy serialization for issues like John had to make sure that zerocopy is zerocopy indeed.

**Comment by biddisco** [comment]
I'll be making tests of that kind for sure. Once I've ironed out the verbs stuff, I would like to extent serialization_buffer to parcelport_buffer which would do the same, but use memory allocated by the parcelport - this would then truly allow for zero copy.

**Comment by hkaiser** [comment]
> @aserio the serialization is unit tested already, what tests do you miss?

Polymorphic serialization is unit tested indeed. We have tests for zero-copy serialization and array optimizations, for instance.

**Comment by AntonBikineev** [comment]
Polymorphic serialization for pointers requires type to be default-constructed (IIRC Boost.Serialization requires the same) Currently I have no idea how to implement it for types without default constructors.

**Comment by gentryx** [comment]
Does the snippet below help? That's how I treat one of our objects in LibGeoDecomp w/o default c-tor in Boost::Serialization. I'm not sure though if we've ever used this with polymorphic pointers though.


   namespace boost {
   namespace serialization {

   template<class Archive, typename CELL_TYPE>
   inline void load_construct_data(Archive& archive, LibGeoDecomp::TracingBalancer *object, const unsigned version)
   {
       ::new(object)LibGeoDecomp::TracingBalancer(0);
       serialize(archive, *object, version);
   }
   
   }
   }

**Comment by hkaiser** [comment]
After a longish discussion we decided to remove the last two bullets from above to maintain maximum user code compatibility with Boost.Serialization. Please raise objections, if needed.

**Comment by hkaiser** [comment]
@AntonBikineev Do you plan to work on replacing the `serialize_sequence` facility, still? Otherwise we'd be able to close this.

**Comment by AntonBikineev** [comment]
@hkaiser, @K-ballo: do you see this as an issue or improvement? I don't know whether we need this or not, there was a discussion about it on IRC I don't remember the idea of..

**Comment by sithhell** [comment]
It should be just replacing `serialize_sequence (ar, seq)` with `ar & seq`.

**Comment by K-ballo** [comment]
As long as all `seq` are `hpx::util::tuple`, that should work. Tuple is no longer using `serialize_sequence`.

**Comment by AntonBikineev** [comment]
I would also like to add a new issue of serialization, namely make serialize_buffer the only type capable of being zero-copy serialized (we talked to @sithhell about it briefly). Although it doesn't give a problem for parcel serialization, it's not consistent and makes this normal code broken: https://gist.github.com/AntonBikineev/3e4bd54936286e0a329a
Currently at new job I'm stuck with C++98, Java, Cobra and other technologies and might not be able to fix this by the time of new release.

**Comment by sithhell** [comment]
I don't think we should limit zero copy optimization for `serialize_buffer` only. When we use serialization internally, we keep the data alive long enough. When a external user uses zero copy optimization, lifetime should be enforced properly. It's an advanced feature for optimization and I think any data type should be able to take advantage of that.

**Comment by hkaiser** [comment]
Can this be closed now?

**Comment by AntonBikineev** [comment]
Yes, I think so.
