### ISSUE TITLE
More executor changes

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1544]
After merging the first batch of changes related to executors (see #1510), there is a list of things to implement to finalize their design and integration with the rest of the code base:
- [x] allow `dataflow` to be used with executors (#1545)
- [x] allow `.then()` to be used with executors (#1547)
- [x] remove `.on()` functionality from the existing 'shim' execution policies (inhibit chaining of `.on()` calls) (#1556)
  - This will have to be re-added for the `.with()` functionality. We need to investigate if disable chaining `.on()` only is possible (and sensible to do).
- [x] enable all existing parallel algorithms to be usable with execution policies generated by `.on()` (#1567)
- [x] create a NUMA aware executor (run tasks on _this_ NUMA domain) (#1741)
- [ ] integrate executors with `hpx::partitioned_vector` and `hpx::unordered_map` to enable seamless SPMD style of execution
- [x] integrate executors with distribution policies (e.g. run tasks on _this_ locality, etc.) (#1701, #1713)
- [x] inhibit generic `execution_policy` from being instantiated by 'shim' execution policies (#1679)
- [x] make use of executor traits' bulk functionality in each of the partitioners
  - [x] for_each_partitioner: #1622 
  - [x] static_partitioner: #1685
  - [x] scan_partitioner: #1696
- [x] Extend executor interface to support timed scheduling (#1709, #1717)
- [x] Add `.with()` to execution policies allowing attaching an `executor_parameter_traits<Executor>` which customizes various scheduling parameters, like chunking (#1700)
- [x] Add this-thread-executor (needed to support HPXRx) (#1669, #1695)
- [x] Unify `parallel_executor` and `parallel_fork_executor` (#1721)

**Comment by sithhell** [comment]
Am 23.05.2015 5:47 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>

> create a NUMA aware executor (run tasks on this NUMA domain)

This will be a tough one, not only do we want to confine tasks to run on
`this` NUMA domain only, we also want to be able to partition a set of
tasks over different NUMA domains. This needs to be closely coordinated
with the GSoC project. I think proper resource sharing of the available
hardware resources is a mandatory pre condition to that.

> integrate executors with hpx::vector and hpx::unordered_map to enable
seamless SPMD style of execution
> integrate executors with distribution policies (e.g. run tasks on this
locality, etc.)

Another important aspect is to associate actions with executors.

**Comment by hkaiser** [comment]
> Another important aspect is to associate actions with executors.

That's what I meant when I wrote ' integrate executors with distribution policies'

**Comment by sithhell** [comment]
Am 23.05.2015 7:55 nachm. schrieb "Hartmut Kaiser" <notifications@github.com
>:
>>
>> Another important aspect is to associate actions with executors.
>
> That's what I meant when I wrote ' integrate executors with distribution
policies'

Distribution policies would take care of this at the caller site indeed. A
challenge will be heterogeneous systems.
What I had in mind was choosing a executor at the callee site (for example
a component could decide where the action is run, aligned with the policy
engine for example).

**Comment by hkaiser** [comment]
> What I had in mind was choosing a executor at the callee site (for example a component could decide where the action is run, aligned with the policy engine for example).

Sure, but this is not what the `executor_traits` are meant to be used for. They are used for selecting the proper agent at the call site.

**Comment by sithhell** [comment]
Am 23.05.2015 11:40 nachm. schrieb "Hartmut Kaiser" <
notifications@github.com>:
>>
>> What I had in mind was choosing a executor at the callee site (for
example a component could decide where the action is run, aligned with the
policy engine for example).
>
> Sure, but this is not what the executor_traits are meant to be used for.
They are used for selecting the proper agent at the call site.

One could think of a component as an executor. They already have a
`schedule_thread ` function after all. Using `executor_traits` for that as
well makes sense to me.

**Comment by hkaiser** [comment]
> One could think of a component as an executor. They already have a `schedule_thread ` function after all. Using `executor_traits` for that as well makes sense to me.

You will have to elaborate (help). Even after thinking about it some more I was not able to make the concepts fit.

**Comment by hkaiser** [comment]
@heller I realized that we have an example demonstrating how to bind the execution of all actions of a particular component to a specified executor: https://github.com/STEllAR-GROUP/hpx/blob/master/examples/quickstart/component_with_executor.cpp

Would this be what you were looking for?

**Comment by hkaiser** [comment]
@sithhell see above, pls

**Comment by sithhell** [comment]
It still seems very low level, but a start. What's missing is a way to
select executors on an action by action basis.

**Comment by sithhell** [comment]
Moving this to 1.0.0.
