### ISSUE TITLE
Extend inspect tool

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#1559]
The inspect tool should be extended to detect violations of more coding guidelines and to ensure we use certain functionalities consistently. Here is a possible list of inspect checker to add:

- [x] line length shouldn't exceed 80 characters (soft limit), and 90 characters (hard limit) (#1683)
- [x] no trailing whitespace (#1583)
- [x] don't use `boost::move`, use `std::move` instead (#1603)
- [x] don't use `std::begin`/`std::end` as some compilers don't support it (yet), use `boost::begin`/`boost::end` instead  (#1603)
- [x] ~~spell check *.qbk and doxygen comments~~
- [x] Let generated filename/line information into link pointing to the line on the correct commit on github
- [ ] don't use `#include <hpx/hpx_fwd.hpp>` 

Also:

- [x] the generated report should have a clickable logo referring to the github repository of HPX  (#1604)

**Comment by Bcorde5** [comment]
I will take on the clickable logo request.
