### ISSUE TITLE
Add index-based for-loops

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2016]
Index-based parallel for-loops have been proposed for standardization here: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0075r1.pdf. While the currently proposed interfaces may still change, having an implementation in HPX would provide valuable implementation experience.

Here is a list of the constructs related to index-based for-loops:

- [x] `for_loop` (#2018)
- [ ] `for_loop_n` (#2059)
- [x] `for_loop_strided` (#2018)
- [ ] `for_loop_n_strided`  (#2059)
- [x] `induction` (#2018)
- [x] `reduction` `reduction_plus` `reduction_multiplies` `reduction_min` `reduction_max` (#2018)
- [x] `reduction_bit_and` `reduction_bit_or` `reduction_bit_xor` (#2018)
