### ISSUE TITLE
Implement datapar for parallel algorithms

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2333]
Here is the list of all parallel algorithms. We plan to enable most (if not all) to support `datapar`, `datapar(task)` and variations.
- [x] `adjacent_difference` (#5580)
- [x] `inner_product` (see #2330)
- [ ] `adjacent_find` 
- [ ] `all_of` `any_of` `none_of` 
- [x] `copy` `copy_n` (#5428)
- [ ] `copy_if` 
- [ ] `move`
- [x] `count` `count_if` (see #2330)
- [ ] `equal` `mismatch` 
- [ ] `exclusive_scan` `inclusive_scan` 
- [ ] `reduce` 
- [x] `transform` (see #2330)
- [x] `fill` `fill_n` (#5465)
- [ ] `find` `find_end` `find_first_of` `find_if` `find_if_not` 
- [x] `for_each` `for_each_n` (see #2330)
- [x] `generate` `generate_n` (#5594)
- [ ] `is_heap` `is_heap_until`
- [ ] `is_partitioned` `is_sorted` `is_sorted_until` 
- [ ] `lexicographical_compare` 
- [ ] `max_element` `min_element` `minmax_element` 
- [ ] `partial_sort` `partial_sort_copy` `nth_element` `sort` `stable_sort`
- [ ] `partition` `partition_copy` `stable_partition` 
- [ ] `remove` `remove_if` 
- [ ] `remove_copy` `remove_copy_if`
- [ ] `replace` `replace_copy` `replace_copy_if` `replace_if`
- [ ] `reverse` `reverse_copy`
- [ ] `rotate` `rotate_copy`
- [ ] `search` `search_n`
- [ ] `set_difference` `set_intersection` `set_symmetric_difference` `set_union` `includes`
- [ ] `inplace_merge` `merge`
- [ ] `swap_ranges`
- [ ] `transform_reduce`
- [ ] `transform_exclusive_scan` `transform_inclusive_scan`
- [ ] `uninitialized_copy` `uninitialized_copy_n`
- [ ] `uninitialized_fill` `uninitialized_fill_n`
- [ ] `unique` `unique_copy`

**Comment by msimberg** [comment]
Removing the milestone as the individual issues can be scheduled for milestones instead (and it's unlikely that all of them will be done for one milestone).

**Comment by hkaiser** [comment]
This is not done yet - reopening.
