### ISSUE TITLE
Adapt execution policy name changes from C++17

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2390]
While the Parallelsim TS has been now adopted tobe part of C++17, there have been a couple of name changes which require corresponding changes in HPX:

 - [x] `par_vec` has been renamed to `par_unseq` (see #2436)
 - [x] execution policies now live in `namespace std::execution`  (see #2436)
 - [x] execution policies now don't have `'execution'` in their name anymore (i.e. the former  `std::sequential_execution_policy` is now named `std::execution::sequential_policy`)  (see #2436)
 - [x] the header `<execution_policy>` is now named `<execution>`  (see #2436)
 - [x] `inner_product` was renamed to `transform_reduce` (see #2437)
 - [x] various parameter sequence changes have been adopted (for `transform_reduce` etc.) (see #2437)

Other changes (we need to decide whether we will adopt those):

 ~- [ ] any exception thrown from any of the algorithms now calls `std::terminate`~
 ~- [ ] the algorithm `adjacent_difference` has been removed~

**Comment by biddisco** [comment]
"any exception thrown from any of the algorithms now calls std::terminate"

Why on earth was this decided. I agree that its hard to recover from an error, but calling terminate sounds very drastic.

**Comment by hkaiser** [comment]
> Why on earth was this decided. I agree that its hard to recover from an error, but calling terminate sounds very drastic.

I agree completely and I don't think we should follow down that path. The way the wording is done now is that the exception behavior is defined by the execution policy and all standardized policies (`std::execution::seq`, `std::execution::par`, and `std::execution::par_unseq`) will cause for the algorithms to call `std::terminate` in case of any exceptions. This leaves us free to do whatever we seem to be appropriate.

The rationale was that there was not sufficient time for C++17 to come up with a (proper) solution. Any other half-solution would have caused breaking changes down the road. Since `par_unseq` is not implementable using exceptions (and the spec always mandated calling `std::terminate` in this case, the majority opinion was to unify the behavior. the alternative would have been to completely rip out the parallel algorithms.
