### ISSUE TITLE
Implement executor proposal (P0443R0)

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2439]
The corresponding document can be found here: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0443r0.html

The following sub-tasks should be solved:

- [x] Implement lower-level customization points which can be used to implement the specified APIs (customization points). This should be fully generic, variadic interfaces. Functionality missing from the executor implementations should be emulated by the customization point implementations (see #2447).
  - `OneWayExecutors` should implement `sync_execute`, possibly `apply_execute`
  - `TwoWayExecutors` should additionally implement `async_execute` and optionally `then_execute`
  - `BulkOneWayExecutors` may optionally implement `sync_bulk_execute` (note, the name is deliberately different from specification).   - `BulkTwoWayExecutors` may additionally implement `async_bulk_execute` and `then_bulk_execute`. 
- [x] Change implementation of existing executors to support new APIs (see #2447), 
  - Add new traits (`is_one_way_executor`, `is_two_way_executor`, etc.)
  - Port `sequenced_executor` and `parallel_executor` to support new customization points. 
- [x] Create customization point specializations for the thread-executors (see #2447).
- [x] Create customization point specializations disptaching through `executor_traits`  to support old executors (see #2447).
- [x] Port all existing code from using the traits APIs to the new customization points (algorithms, other facilities) (see #2447)
- [x] Create executors which will provide timed execution services on top of some given 'base'-executor. Those will replace the `timed_executor_traits` (see #2453).
- [x] Create customization points for timed execution based on timed executors, implement those for `threads::executors` (see #2453).
- [ ] Create replacement APIs for existing parameter and information traits. This would also involve changing the current structure of the execution policies. Currently, an execution policy stores both, an executor and a parameter object. In the future, the parameter object should become part of the executors itself (see #2915).
- [ ] Create customization points as specified by P0443. We still expect for this document to change. This might involve the creation of special wrapping executors. (see #2915)

The general goal would be to create a set of very modular executors which can be combined to achieve special scheduling behavior.
