### ISSUE TITLE
Adapt executor implementation to P0443R2

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#2691]
This involves a couple of steps. The (currently still evolving) document can be found here: https://github.com/executors/issaquah_2016/blob/R2/wording.md

- [x] clean up existing executor categories and corresponding traits (#2693)
- [x] rename `<op>_bulk_execute` to `bulk_<op>_execute` (#2693)
- [ ] implement `BaseExecutor` requirement on all existing executors
- [x] implement traits `has_<op>_member<T>` (#2693)
- [ ] implement traits `has_<op>_free_function<T>`
- [ ] support free functions when invoking executors (use traits above to distinguish)
- [ ] implement traits reporting on customization points `can_<op><T>`
- [ ] implement `task_block` overload taking executor (as an alternative to the existing overload taking an execution policy)
- [ ] add `executor_execution_mapping_guarantee`
- [ ] add `executor_execute_blocking_guarantee`
- [ ] add `executor_bulk_forward_progress_guarantee`
- [ ] implement polymorphic executor wrappers
- [ ] implement default `one_way_executor`, `two_way_executor`, and `never_blocking_one_way_executor`
- [ ] implement non-variadics interface requirements of P0443R2 on top of our variadic interfaces

**Comment by msimberg** [comment]
@hkaiser we can probably close this now? I think it's unlikely that we'll go back and fill in the gaps for an old proposal. We can track the current progress in #5045.
