### ISSUE TITLE
Suspension of runtime

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3003]
This is to collect feedback/wishes on suspending the runtime (putting threads to sleep rather than shutting down the whole runtime).

The main use case is situations where HPX cannot be used for the whole application (e.g. replacing OpenMP in an application that already uses MPI & OpenMP). This makes it easier for users to start integrating HPX piecewise into existing applications.

Currently this only considers running and suspending HPX on a single node (as communication between nodes would be handled by e.g. MPI in the cases where this is useful). As this is a big issue it will be split into separate PRs. What needs to be done is:

- [x] suspend single threads (#3046)
- [x] suspend full pools (#3080)
- [x] suspend the full runtime (#3129)
- [x] documentation (#3152)

# Suspending single threads

This can be done using condition variables. What could be useful is a mode for selecting how to remove/suspend a pu: stop scheduler immediately, wait for work queues to be empty, and wait for thread map and queues to be empty. The current `remove_processing_unit` would normally use the "wait for thread map and queues to be empty" mode at shutdown, and the to-be-added `suspend_processing_unit` would normally use the "wait for work queues to be empty" mode.

*Note*: it's not clear to me if it's best to let each pu itself (i.e. `scheduling_loop`) handle when it's okay to stop the loop (like waiting for thread map to be empty), or if this should be handled externally (like waiting for thread count to be `1 + background_thread_count`), or both. The latter is likely a must, but the former I'm not sure about. This applies to suspending pools and the runtime as well.

# Suspending pools

This seems to be mostly wrapping appropriate/already existing calls (is it?) to get something like `suspend_pool("pool-name", suspend_mode)`. The notes about different modes of suspending apply here as well.

# Suspending the runtime

This can most likely reuse the mechanism for waiting for `hpx::finalize`, but rather than stopping and cleaning everything up it would tell the thread manager to suspend all pools and threads. Again, different modes of suspending apply here.

Deciding on the API is not critical right now but it will need some time to brew in people's minds, so to get started below are a few thoughts.

If the current `init/start/stop/finalize` API should not be broken, usage could look something like this:
```
// Start runtime without a function to run
hpx::start(argc, argv);

...

// Run hpx_function_1 on runtime, start runtime if needed
// Suspend when done
hpx::init(hpx_function_1, mode_suspend);

// Run hpx_function_2 on runtime, don't block
hpx::start(hpx_function_2);

// Wait and suspend when done
hpx::stop(mode_suspend);

...

// Stop the runtime, same as hpx::stop(mode_shutdown)
hpx::stop();

...

// Same as current behavior, same as hpx::init(hpx_function_4, argc, argv, mode_shutdown)
hpx::init(hpx_function_3, argc, argv);
```

Note that `hpx::finalize` should not require any changes (at least in usage).

If the current API can be changed anything is possible... E.g. I would expect an `init` function to only initialize the runtime and not be used for starting tasks on the runtime. Ideas welcome.

Potential additions:
```
// Allowing non-nullary functions and returning the result
result_type result = hpx::init(hpx_function, arg1, arg2, ...);
...
// More?
```

# Questions

- Are different suspension modes useful or necessary?
- What other use cases are there?

**Comment by hkaiser** [comment]
@msimberg can this be closed now? It looks like it...

**Comment by msimberg** [comment]
@hkaiser Yes, it can be closed.
