### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3044]
Currently the following tests fail regularly on buildbot:

- [x] [`tests.unit.parallel.inplace_merge`](http://rostam.cct.lsu.edu/builders/hpx_clang_3_8_boost_1_59_centos_x86_64_debug/builds/134/steps/run_unit_tests/logs/tests.unit.parallel.algorithms.inplace_merge%20%2817.02%20sec%29) (#2964)
- [x] [`tests.unit.threads.distributed.mpi.thread_stacksize`](http://rostam.cct.lsu.edu/builders/hpx_gcc_4_9_boost_1_56_centos_x86_64_release/builds/113/steps/run_unit_tests/logs/tests.unit.threads.distributed.mpi.thread_stacksize%20%280.95%20sec%29) (#3097, clang 4 debug)
- [x] [`tests.unit.threads.distributed.tcp.thread_stacksize`](http://rostam.cct.lsu.edu/builders/hpx_gcc_4_9_boost_1_56_centos_x86_64_release/builds/113/steps/run_unit_tests/logs/tests.unit.threads.distributed.tcp.thread_stacksize%20%280.35%20sec%29) (#3097, clang 4 debug)
- [x] [`tests.unit.util.pack_traversal_async`](http://rostam.cct.lsu.edu/builders/hpx_gcc_4_9_boost_1_59_centos_x86_64_debug/builds/116/steps/run_unit_tests/logs/tests.unit.util.pack_traversal_async%20%280.30%20sec%29)
- [x] [`tests.unit.parallel.executors.minimal_timed_async_executor`](http://cdash.cscs.ch/viewBuildError.php?buildid=68202) (#3058)
- [x] [`tests.unit.parallel.timed_parallel_executor`](http://cdash.cscs.ch/viewBuildError.php?buildid=68202) (#3058)
- [ ] `tests.unit.lcos.distributed.tcp.async_continue_cb_colocated` (#2935)
- [ ] `tests.unit.lcos.distributed.tcp.async_cb_remote_client` (#2935)
- [x] [`tests.unit.parallel.executors.executor_parameters`](http://cdash.cscs.ch/testDetails.php?test=11006033&build=68227)
- [x] [`tests.regressions.util.command_line_required_arguments_2990`](http://rostam.cct.lsu.edu/builders/hpx_clang_3_8_boost_1_59_centos_x86_64_debug/builds/134/steps/run_regression_tests/logs/tests.regressions.util.command_line_required_arguments_2990%20%281.11%20sec%29) (could be related to #2931? shows the same error)
- [x] [`tests.regressions.lcos_dir.distributed.mpi.after_588`](http://rostam.cct.lsu.edu/builders/hpx_gcc_6_boost_1_64_centos_x86_64_release/builds/119/steps/run_regression_tests/logs/tests.regressions.lcos_dir.distributed.mpi.after_588%20%281.18%20sec%29)
- [x] [`tests.regressions.lcos_dir.distributed.tcp.after_588`](http://rostam.cct.lsu.edu/builders/hpx_gcc_6_boost_1_64_centos_x86_64_release/builds/119/steps/run_regression_tests/logs/tests.regressions.lcos_dir.distributed.tcp.after_588%20%280.48%20sec%29)
- [x] [`tests.regressions.lcos_dir.distributed.mpi.after_588_4`](http://rostam.cct.lsu.edu/builders/hpx_gcc_6_boost_1_64_centos_x86_64_release/builds/119/steps/run_regression_tests/logs/tests.regressions.lcos_dir.distributed.mpi.after_588_4%20%281.04%20sec%29)
- [x] [`tests.regressions.lcos_dir.distributed.tcp.after_588_4`](http://rostam.cct.lsu.edu/builders/hpx_gcc_6_boost_1_64_centos_x86_64_release/builds/119/steps/run_regression_tests/logs/tests.regressions.lcos_dir.distributed.tcp.after_588_4%20%280.36%20sec%29)
- [x] [`tests.regressions.lcos_dir.future_hang_on_then_629`](http://rostam.cct.lsu.edu/builders/hpx_gcc_6_boost_1_64_centos_x86_64_release/builds/119/steps/run_regression_tests/logs/tests.regressions.lcos_dir.future_hang_on_then_629%20%280.93%20sec%29)
- [x] [`tests.regressions.lcos_dir.future_hang_on_wait_with_callback_629`](http://rostam.cct.lsu.edu/builders/hpx_gcc_6_boost_1_64_centos_x86_64_release/builds/119/steps/run_regression_tests/logs/tests.regressions.lcos_dir.future_hang_on_wait_with_callback_629%20%280.78%20sec%29)
- [X] [`tests.regression.performance_counters.papi_counters_active_interface`](http://rostam.cct.lsu.edu/builders/hpx_clang_3_8_boost_1_59_centos_x86_64_debug/builds/134/steps/run_regression_tests/logs/tests.regressions.performance_counters.papi_counters_active_interface%20%281.10%20sec%29) (#3099)
- [x] `tests.unit.components.distributed.mpi.action_invoke_no_more_than` (#3043)
- [x] `tests.unit.components.distributed.tcp.action_invoke_no_more_than` (#3043)
- [x] `tests.regressions.actions.distributed.mpi.component_action_move_semantics` (#3038)
- [x] `tests.regressions.actions.distributed.tcp.component_action_move_semantics` (#3038)
- [x] `tests.regressions.actions.distributed.mpi.plain_action_move_semantics` (#3038)
- [x] `tests.regressions.actions.distributed.tcp.plain_action_move_semantics` (#3038)
- [x] `tests.unit.parallel.executors.thread_pool_executors` (timeout, up for removal at #3077)
- [ ] `tests.unit.parallel.algorithms.inclusive_scan_executors_v1` (timeout, same as `thread_pool_executors`?)
- [x] [`tests.unit.components.distributed.tcp.migrate_component`](http://rostam.cct.lsu.edu/builders/hpx_clang_3_8_boost_1_59_centos_x86_64_release/builds/191/steps/run_unit_tests/logs/tests.unit.components.distributed.tcp.migrate_component%20%28Timeout%29) (timeout, #3164)
 - [x] [`tests.unit.components.distributed.mpi.migrate_component`](http://rostam.cct.lsu.edu/builders/hpx_clang_3_9_boost_1_61_centos_x86_64_debug/builds/211/steps/run_unit_tests/logs/tests.unit.components.distributed.mpi.migrate_component%20%284.88%20sec%29) (timeout, #3164)
 - [x] [`tests.regressions.lcos_dir.wait_for_1751`](http://rostam.cct.lsu.edu/builders/hpx_gcc_4_9_boost_1_58_centos_x86_64_debug/builds/199/steps/run_regression_tests/logs/tests.regressions.lcos_dir.wait_for_1751%20%282.25%20sec%29) (#3153, #3158)

If you know of any tests that are missing from the list or have been fixed, please update the list or comment.

**Comment by sithhell** [comment]
The move semantics tests have been fixed by #3038.

**Comment by hkaiser** [comment]
@msimberg could you add a link for each failing test pointing to the build logs, please?

**Comment by msimberg** [comment]
@hkaiser Good idea. I've added links to test/build failures. Some I've removed as they don't seem to fail anymore on the latest commits but I'll keep an eye on them in case they still pop up.

**Comment by hkaiser** [comment]
Re-opening as this was closed accidentally.

**Comment by sithhell** [comment]
I just added a few more that keep appearing since the latest merges.
