### ISSUE TITLE
Version 1.1.0 must-haves

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#3050]
This is to track/discuss issues that *have* to be fixed for the 1.1.0 release.

- [ ] Fix failing tests (#3044)
- [ ] Fix/remove failing examples (#3049)
- [x] resolve hwloc build issues (#2977, #2996, #3133)
- [x] Consistently use executors to schedule work (#3039)
- [x] Fix build warnings (when possible, see #3079, #3084)
- [x] Do not bind test running to cmake test build rule (#3052)
- [x] Assertion failure when using bulk hpx::new_ in asynchronous mode (#3054, #3087)
- [x] Fix linker problem in MSVC release mode (#3060)
- [x] Adapt MSVC C++ mode handling to VS15.5 (#3061)
- [x] Addressing breaking changes in Boost V1.66 (#3085)
- [x] Disable default executor compatibility with V1 executors (#3119)
- [x] Compilation of parallel algorithms with HPX_WITH_DATAPAR is broken (#3165)

Please add or comment about missing items.

**Comment by taeguk** [comment]
How about including #2325 ? Because ```seq``` is now used for temporarily avoiding that problem, the parallel algorithms use scan_partitioner have very bad performance.

**Comment by msimberg** [comment]
I'm closing this now in favor of individual tickets for remaining failures.
