### ISSUE TITLE
HPX Modularization

### ISSUE THREAD

**Issue by sithhell** [STEllAR-GROUP/hpx#3636]
This is a follow-up on #3546 to track all relevant work and refine the process further.
#3546 outlines a very coarse modular structure, this ticket is, however, proposing to start with fine-grained modules to ease the transition and starts with a small set of independent entities.
- [x] General layout and helpers for modularization (#3582)
- [x] Preprocessor programming (#3629)
- [x] Configuration macros (and possibly also cmake scripts, #3832)
- [x] Cache (#3870, #3927)
- [x] Testing related facilities (including cmake helper functions, #3971)
- [x] Assert (#3628)
- [x] Format (#3976)
- [x] Logging (#3980)
- [x] Utilities (#3979)
- [x] Timing (#3985)
- [x] Threading (#4399)
- [x] Thread pools (#4399)
- [x] Algorithms (#3957)
- [x] Segmented algorithms (#3981)
- [x] Execution (#3982)
- [x] Executors
- [x] Thread executors
- [x] Local runtime (partly in #4091)
- [x] Serialization (#4114)
- [x] AGAS (#5144)
- [x] Parcelset
- [x] Components (component_base: #4527)
- [x] Actions (actions_base, actions: #4527)
- [x] Performance counters (distributed #4430)
- [x] Applier (can be removed completely, requires some restructuring)
- [x] Naming (naming_base: #4602)
- [x] Local LCOs (#4231)
- [x] Distributed LCOs (#4518)
- [x] Testing (#3971)
- [x] Topology (#4019)
- [x] Error handling (#4000)
- [x] Collectives (#3931, #3950)
- [x] Resiliency (#4037)
- [x] Concurrency (#4020)
- [x] FileSystem (#4036)
- [x] Functional (#4045)
- [x] ProgramOptions (#4040)
- [x] Plugin (#4050)
- [x] BasicExecution (#4090)
- [x] Coroutines (#4099)
- [x] Compute (#4136)
- [x] ComputeCuda (#4136)
- [x] Memory (#4138)
- [x] Checkpointing (#4178)
- [x] Resource partitioner (#4147)
- [x] Thread manager (#4147)
- [x] Affinity (#4164)
- [x] Batch environment (#4164)
- [x] Data structures (#4113)
- [x] lexical_cast (#4288)

This list is likely to grow in the future as we move on.

**Comment by gonidelis** [comment]
> We can close this as we have finished modularization now.

Does this mean that Modularization is complete 100%?

**Comment by hkaiser** [comment]
> > We can close this as we have finished modularization now.
> 
> Does this mean that Modularization is complete 100%?

Well, I'd say 99%. There are some minor things that are missing - mostly related to the build system, also we need to move some of the tests to their corresponding modules.
