### ISSUE TITLE
Parallel algorithms should accept iterator/sentinel pairs

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#3646]
Our parallel algorithms currently expect for the begin/end iterator pairs to be of the same type. This is an unnecessary limitation. We should relax that. 

Here is the list of algorithms that need to be adapted:

- [x] `adjacent_difference` (#5564)
- [x] `adjacent_find`  (#4996)
- [x] `all_of` `any_of` `none_of`
- [x] `copy` `copy_if` (#4821)
- [x] `move`
- [x] `count` `count_if`
- [x] `equal` (#4883) `mismatch` (#4884)
- [x] `exclusive_scan` (#5436)
- [x] `inclusive_scan` (#5439)
- [x] `reduce` (see #3650, #4836)
- [x] `transform` (#4855, #4888, #5051)
- [x] `fill`  (#4860)
- [x] `find` `find_end` `find_first_of` `find_if` `find_if_not`  (#4885)
- [x] `for_each`  `for_each_n` (#4867)
- [x] `for_loop` `for_loop_strided` `for_loop_n` `for_loop_strided_n` (#4980)
- [x] `generate` `generate_n` (#4896)
- [x] `is_heap` `is_heap_until` (#4965)
- [x] `is_partitioned` (#5006)
- [x] `is_sorted` `is_sorted_until` (#5025)
- [x] `lexicographical_compare` (#5350)
- [x] `max_element` `min_element` `minmax_element` (#5241)
- [x] `make_heap` (#4964)
- [x] `sort` (#5460)
- [x] `partial_sort` `partial_sort_copy` (#5630)
- [x] `nth_element` (#5592)
- [x] `stable_sort` (see #4803)
- [x] `partition` `partition_copy` `stable_partition` (#5540)
- [x] `remove` `remove_if` (#5125)
- [x] `remove_copy` `remove_copy_if` (#5150)
- [x] `replace` `replace_copy` `replace_copy_if` `replace_if` (#5192)
- [x] `reverse` `reverse_copy` (#5225)
- [x] `rotate` `rotate_copy` (#5459)
- [x] `search` (#5066)
- [x] `set_difference` `set_intersection` `set_symmetric_difference` `set_union` `includes` (#4970)
- [x] `merge` `inplace_merge` (#4970)
- [x] `swap_ranges` (#5449)
- [x] `uninitialized_copy` `uninitialized_copy_n` (#5371)
- [x] `uninitialized_fill` `uninitialized_fill_n` (#5402)
- [x] `uninitialized_default_construct` `uninitialized_default_construct_n` (#5415)
- [x] `uninitialized_value_construct` `uninitialized_value_construct_n` (#5416)
- [x] `uninitialized_move` `uninitialized_move_n` (#5389)
- [x] `unique` `unique_copy` (#5458)
- [x] `transform_reduce` (#4925)
- [x] `transform_exclusive_scan` (#5440) `transform_inclusive_scan` (#5444)
- [x] `destroy` `destroy_n` (#4869)

**Comment by gonidelis** [comment]
@hkaiser Should we link the relevant Technical Specification to the description?

**Comment by hkaiser** [comment]
> @hkaiser Should we link the relevant Technical Specification to the description?

Sure, please feel free to do that, thanks!

**Comment by gonidelis** [comment]
[Related TS](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4861.pdf)

**Comment by gonidelis** [comment]
@hkaiser Please replace the obsolete `transform` PRs with the new one #5051. Thanks :)
