### ISSUE TITLE
Move tests left behind to respective modules

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#4046]
During the recent modularization efforts we have left behind some of the tests that should be part of the modules. Here is a list of those (there could be more):

- module `datastructures`:
  - [x] `unit/util/tuple.cpp` (#4079)
  - [x] `regression/util/optional_swap_3200.cpp` (#4079)
  - [x] `regression/util/tuple_serialization_803.cpp` (#4079)
  - [x] `unit/traits/is_tuple_like.cpp` (#4049)

- module `errors`:
  - [x] `unit/diagnostics/exception.cpp` (#4049)
  - [ ] `unit/diagnostics/handled_exception.cpp` (#4570)
  - [ ] `unit/diagnostics/unhandled_exception.cpp` (#4570)

- module `iterator_support`:
  - [x] `unit/util/iterator/iterator_adaptor.cpp` (#4079)
  - [x] `unit/util/iterator/iterator_facade.cpp` (#4079)
  - [x] `unit/util/iterator/stencil3_iterator.cpp` (#4179)
  - [x] `unit/util/iterator/transform_iterator.cpp` (#4179)
  - [x] `unit/util/iterator/transform_iterator2.cpp` (#4179)

**Comment by aurianer** [comment]
On it !

**Comment by aurianer** [comment]
Actually, for the iterator, we can't move them because of their dependencies to main hpx headers that can't be moved into the `iterator_support` module

**Comment by hkaiser** [comment]
@aurianer I think those tests can be easily changed not to depend on `hpx/hpx.hpp` anymore. I'd be surprised if those used anything beyond `hpx::init` and friends (as do all the other tests).

**Comment by msimberg** [comment]
It looks like the `transform_iterator` tests and can't be moved as they depend on `result_of.hpp` (`invoke_result`) which are in #4045. This includes `stencil3_iterator.cpp` as well.

`iterator_adaptor.cpp` and `iterator_facade.cpp` should be possible to move though (the headers are already in the `iterator_support` module).

So far we've also added tests that use the runtime to modules, even though that means the modules are not actually fully standalone. As long as no-one is asking to actually use them standalone I prefer keeping the tests with the modules.

**Comment by hkaiser** [comment]
> It looks like the transform_iterator tests and can't be moved as they depend on result_of.hpp (invoke_result) which is in #4045. This includes stencil3_iterator.cpp as well.

Yah, the function module is a fairly fundamental one...

> So far we've also added tests that use the runtime to modules, even though that means the modules are not actually fully standalone. As long as no-one is asking to actually use them standalone I prefer keeping the tests with the modules.

Absolutely! Sorry if I mis-voiced what I was thinking.
