### ISSUE TITLE
HEP 2 implementation tracker

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4656]
This issue tracks how much of #4626 has been implemented. Since HEP 2 is still in progress, this is not necessarily a complete list of things that need to be done.

Headers:

- [ ] `hpx/algorithm.hpp`
- [ ] `hpx/any.hpp`
- [ ] `hpx/barrier.hpp`
- [ ] `hpx/chrono.hpp`
- [ ] `hpx/condition_variable.hpp`
- [ ] `hpx/exception.hpp`
- [ ] `hpx/execution.hpp`
- [ ] `hpx/future.hpp`
- [ ] `hpx/iostream.hpp`
- [x] `hpx/latch.hpp`
- [ ] `hpx/memory.hpp`
- [ ] `hpx/mutex.hpp`
- [ ] `hpx/numeric.hpp`
- [ ] `hpx/optional.hpp`
- [x] `hpx/semaphore.hpp`
- [ ] `hpx/shared_mutex.hpp`
- [ ] `hpx/system_error.hpp`
- [ ] `hpx/thread.hpp`
- [ ] `hpx/tuple.hpp`
- [ ] `hpx/runtime.hpp`
- [ ] `hpx/distributed/algorithm.hpp`
- [ ] `hpx/distributed/barrier.hpp`
- [ ] `hpx/distributed/execution.hpp`
- [ ] `hpx/distributed/future.hpp`
- [ ] `hpx/iostream.hpp`
- [ ] `hpx/distributed/latch.hpp`
- [ ] `hpx/distributed/memory.hpp`
- [ ] `hpx/distributed/numeric.hpp`
- [ ] `hpx/distributed/runtime.hpp`

- [ ] Add documentation page with public API
- [ ] update examples to use API headers (#4488)
