### ISSUE TITLE
HEP 1 implementation tracker

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4657]
This issue tracks how much of #4593 has been implemented. Since HEP 1 is still in progress, this is not necessarily a complete list of things that need to be done.

- [x] `hpx_core` #4649
- [x] `hpx_local`
- [ ] (bonus) use object libraries #4135 
- [x] allow choosing runtime type at run time #4646
- [ ] add CMake options for building only `hpx_core` or `hpx_local`

**Comment by msimberg** [comment]
I'll close this, but please reopen if you think this is a better place to track these things. The split of libhpx into multiple libraries has already happened. I think object libraries can be tracked separately, and exposing the different libraries to users is better done in separate projects.
