### ISSUE TITLE
Prefer enum class over unscoped enums

### ISSUE THREAD

**Issue by msimberg** [STEllAR-GROUP/hpx#4702]
We should gradually move all unscoped enums to enum classes.

Some of those listed below could possibly be hidden in some detail namespace...

- [x] `thread_state_enum`
- [x] `thread_state_ex_enum`
- [x] `thread_stacksize`
- [x] `thread_priority`
- [x] `scheduler_mode` (#5809)
- [x] `scheduler_state` (#5809)
- [x] `component_enum_type`
- [x] `id_type::management_type` (#5817)
- [x] `cache::statistics::method` (#5816)
- [x] `commandline_error_mode`
- [x] `hpx::error`
- [x] `hpx::throwmode` (#5820)
- [x] `future_state`
- [x] `performance_counters::counter_type` (#5850)
- [x] `performance_counters::counter_status`
- [x] `performance_counters::discover_counters_mode`
- [x] `agas::service_mode`
- [x] `serialization::archive_flags`
- [x] `serialization::chunk_type`
- [x] `util::exception_type`
- [ ] `hpx_hwloc_membind_policy`
- [x] `message_buffer_append_state` (parcel coalescing) (#6923)
- [x] `distribution_type` (affinity)
- [x] `deque_status_type` (boost lockfree deque)
- [x] `context_state`, `context_exit_state`, `context_exit_status` (coroutines)
- [x] `logging_destination` (logging)
- [x] `partitioner_mode`

… there are more, please add to this list, if needed.

**Comment by gonidelis** [comment]
@hkaiser checked `throwmode`
