### ISSUE TITLE
Adapt parallel algorithms to C++20

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#4822]
Adapt our parallel algorithms to C++20 (http://eel.is/c++draft/#algorithms) 

Here is the list of algorithms mandated by the standard:

- [x] `adjacent_difference` (#5564)
- [x] `adjacent_find` (#4996)
- [x] `all_of` `any_of` `none_of` (#4859)
- [x] `copy` `copy_if` `copy_n` (#4821)
- [x] `move` (#4870)
- [x] `count` `count_if` (#4865)
- [x] `equal` (#4883) `mismatch` (#4884)
- [x] `exclusive_scan` (#5436)
- [x] `inclusive_scan` (#5439)
- [x] `reduce` (#4836) 
- [x] `transform` (#5051)
- [x] `fill` `fill_n` (#4860)
- [x] `find` `find_end` `find_first_of` `find_if` `find_if_not` (#4885)
- [x] `for_each` `for_each_n` (#4867)
- [x] `for_loop` `for_loop_n` `for_loop_strided` `for_loop_strided_n` (#4911)
- [x] `generate` `generate_n` (#4896)
- [x] `is_heap` `is_heap_until` (#4965)
- [x] `is_partitioned` (#5006)
- [x] `is_sorted` `is_sorted_until` (#5025)
- [x] `lexicographical_compare` (#5350)
- [x] `max_element` `min_element` `minmax_element` (#5241)
- [x] `make_heap` (#4964)
- [x] `partial_sort` `partial_sort_copy` (#5630)
- [x] `nth_element` (#5592)
- [x] `sort` (#5460)
- [x] `stable_sort` (#5470)
- [x] `partition` (#5540)
- [x] `partition_copy` (#5540)
- [x] `stable_partition`  (#5540)
- [x] `remove` `remove_if` (#5125)
- [x] `remove_copy` `remove_copy_if` (#5150)
- [x] `replace` `replace_copy` `replace_copy_if` `replace_if` (#5192)
- [x] `reverse` `reverse_copy` (#5225)
- [x] `rotate` (#5459)
- [x] `rotate_copy` (#5459)
- [x] `search` `search_n` (#5066)
- [x] `set_difference` `set_intersection` `set_symmetric_difference` `set_union` `includes` (#4970)
- [x] `inplace_merge`  (#4970)
- [x] `merge`  (#4970)
- [x] `swap_ranges` (#5449)
- [x] `uninitialized_copy` `uninitialized_copy_n` (#5371)
- [x] `uninitialized_fill` `uninitialized_fill_n` (#5402)
- [x] `uninitialized_default_construct` `uninitialized_default_construct_n` (#5415)
- [x] `uninitialized_value_construct` `uninitialized_value_construct_n` (#5416)
- [x] `uninitialized_move` `uninitialized_move_n` (#5389)
- [x] `destroy` `destroy_n` (#4869)
- [x] `unique` (#5458)
- [x] `unique_copy` (#5458)
- [x] `transform_reduce` (#4925)
- [x] `transform_exclusive_scan` (#5440) `transform_inclusive_scan` (#5444)
- [x] `shift_left` `shift_right` (#5466)

**Comment by gonidelis** [comment]
@hkaiser  Please delte `transform` obsolete PRs and replace them with #5051. Thanks :)

**Comment by gonidelis** [comment]
### How to adapt a parallel algorithm to C++20
1. Render the old overload under namespace `parallel` deprecated (e.g. `hpx::parallel::for_each`), according to the [hpx deprecation headers](https://github.com/STEllAR-GROUP/hpx/blob/master/libs/core/config/include/hpx/config/deprecation.hpp). _Be careful on referring to the pending HPX release version_.

2. Change the base implementations (usually found as function objects under namespace `hpx::parallel::v1::detail`) in order to support iterator/sentinel pairs according to [3646](https://github.com/STEllAR-GROUP/hpx/issues/3646) (just differenciate the type of `last` from the type of `first`).

3. Change the result type (if needed) on the base implementations. Mind not to create conflicts with the deprecated overloads. If there is no other way, change the result type on the deprecated overloads, too.

4. Add the C++20 overloads according to the [C++20 Standard](http://eel.is/c++draft/#algorithms), using the [`tag_fallback`/`tag_fallback_invoke`](https://github.com/STEllAR-GROUP/hpx/blob/master/libs/core/functional/include/hpx/functional/tag_fallback_invoke.hpp) _Customization Point Object_ (_CPO_) mechanism.

    1. If the algorithm has a segmented counterpart (under `/libs/full/segmented_algorithms`), provide the segmented overloads using `tag_invoke` instead of `tag_fallback_invoke` under namespace `hpx::segmented` and delete the dispatch functions (the ones with the underscore: e.g. `for_each_`).

5. Adapt the unit tests so they use the overloads under `hpx` and `hpx::ranges` namespaces. 
    1. Mind to add tests for the overloads without an `ExPolicy`, in every test category (`test_<algorithm>`,     `test_<algorithm>_exception`, `test_<algorithm>_bad_alloc`).
    2. Add tests that check the newly introduced `iterator`-`sentinel_value` overloads (`test_<algorithm>_sent`).
    
6. Provide docs for every given overload using the `#if defined(DOXYGEN)` - `#else` - `#endif` directives. 
    1. Mind to pack the docs under namespace `hpx` or namespace `hpx::ranges` accordingly. 
    2. Pay attention to the (possibly) altered result type.
    3. Be careful on documenting the overloads that do not have an `ExPolicy`. No parallelization is happening there.



#### Nitpicks and Tips
- For a given algorithm, the adaptation takes place both under `/libs/parallelism/algorithms/include/hpx/parallel/algorithms/<algorithm>.hpp` (non ranges overloads) and under `/libs/parallelism/algorithms/include/hpx/parallel/container_algorithms/<algorithm>.hpp` (ranges overloads).
- When documenting the adapted algorithms, [cpprefernce](https://en.cppreference.com/w/cpp/algorithm) is a good to place to read about the _effect_ of the algorithm.
- When documenting an algoirthm under `hpx::ranges` namespace, that takes a `Rng` as an ipnut source, there are no inherent `first` and `last` values. Mind to declare at the top that `first` is equivalent to `parallel::util::begin(rng)` and `last` is equivalent to `parallel::util::end(rng)`.
- Disable clang-format for all the template parameters sections that include an `HPX_CONCEPT_REQUIRES_` (`// clang-format off/on`).
- Check our [result types header](https://github.com/STEllAR-GROUP/hpx/blob/master/libs/parallelism/algorithms/include/hpx/parallel/util/result_types.hpp) for the newly introduced C++20 result types.
- We do not need any additional unit tests (overloads without an `ExPolicy`) for any of the `_async` tests.
- Provide `static_assert`ions that check the validity of the iterators for every given overload: the ones with no `ExPolicy` usually use input iterators while the parallel ones use forward iterators.
- The previous bullet should be taken into consideration even for the `Rng` overloads. [Here](https://github.com/STEllAR-GROUP/hpx/blob/master/libs/core/iterator_support/include/hpx/iterator_support/traits/is_range.hpp) are some HPX custom facilities that provide an iterator-based interface for the `Rng` type.
- `std::pair` usually changes to `hpx::parallel::util::in_out_result` and `std::tuple` changes to `hpx::parallel::util::in_in_out_result`. `std::distance`, occasionally used on the base implementations, changes to `detail::distance` in order to support iterator/sentinel pairs.

**Comment by hkaiser** [comment]
This can be closed now! Thanks to everybody helping to implement, debug, and fix things!
