### ISSUE TITLE
HEP: conformance to C++20

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#4871]
This is a meta ticket collecting all issues related to conformance with C++20:

- [x] Implement N4409 on top of HPX (#1141)
- [x] Adapt all parallel algorithms to Ranges TS (#1668)
- [x] Parallel algorithms should accept iterator/sentinel pairs (#3646)
- [x] Add `shift_left` and `shift_right` algorithms (#3706)
- [x] Implement the C++20 Synchronization Library - `barrier`, `latch`, `counting_semaphore`, `binary_semaphore`, `condition_variable`, `condition_variable_any`, `cv_status` (#3983, #4634)
- [x] Implement C++20 Stop Token and Joining Threads (#3994)
- [x] Use C++20 std::source_location where available, adapt ours to conform (#3995, #5807)
- [x] Adapt `hpx::future` to C++20 `co_await` (#4770)
- [x] Adapt parallel algorithms to C++20 (#4822)
- [x] Move algorithms to tag_fallback_dispatch (#5204)

Other issues in current code that need fixing for C++20:

- [x] Add `is_sentinel_for` trait implementation and test (#4745)
- [x] Deprecate result_of and friends (#4749)
- [x] Add `sized_sentinel_for` concept and make distance dispatch according to that (#4768)
- [x] Remove last use of `std::result_of`, removed in C++20 (#4893)
- [x] Move chrono functionality to `hpx::chrono` namespace (#4917)
- [x] Move public `hpx::parallel::execution` functionality to `hpx::execution` (#4943)
- [x] Moving `is_execution_policy` and friends into namespace hpx (#4969)
- [x] Parallel sort fails to compile with C++20 (#4971)
- [x] Removing use of `get_temporary_buffer` and `return_temporary_buffer` (#4972)
- [x] hpx::parallel::fill fails compiling (#5016)
- [x] Lessen constraints on certain algorithm arguments (#5027)

**Comment by hkaiser** [comment]
This can be closed now as all issues listed above have been resolved. Yay! Full conformance to C++20 achieved!

**Comment by gonidelis** [comment]
@hkaiser  Thanks!!!
