### ISSUE TITLE
Move algorithms to tag_fallback_dispatch

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#5204]
Our experience with disentangling the segemented algorithms by the help of utilizing tag_dispatch style overloads has shown that it is helpful to move all existing `tag_dispatch` implementations of the parallel algorithms to use `tag_fallback_dispatch` instead. This allows to use SFINAE on the overloads provided by external specializations. 

Here is a list of algorithms that need to be adapted:

- [x] `adjacent_find` (#5201)
- [x] `all_of` `any_of` `none_of` (#5224)
- [x] `copy` (#5203) 
- [x] `copy_if` `copy_n` (#4821)
- [x] `move` (#4870)
- [x] `count` `count_if` (#5220)
- [x] `equal` (#4883) `mismatch` (#4884)
- [x] `reduce` (#5321)
- [x] `transform` (#5256)
- [x] `fill` (#5307) 
- [x] `fill_n` (#4860)
- [x] `find` `find_if` `find_if_not` (#5308)
- [x] `find_end` `find_first_of` (#4885)
- [x] `for_each` (#5176)
- [x] `for_each_n` (#5212)
- [x] `for_loop` `for_loop_n` `for_loop_strided` `for_loop_strided_n` (#4911)
- [x] `generate` (#5307) 
- [x] `generate_n` (#4896)
- [x] `is_heap` `is_heap_until` (#4965)
- [x] `is_partitioned` (#5006)
- [x] `is_sorted` `is_sorted_until` (#5025)
- [x] `make_heap` (#4964)
- [x] `remove` `remove_if` (#5125)
- [x] `remove_copy` `remove_copy_if` (#5150)
- [x] `search` `search_n` (#5066)
- [x] `set_difference` `set_intersection` `set_symmetric_difference` `set_union` `includes` (#4970)
- [x] `inplace_merge` (#4970)
- [x] `merge` (#4970)
- [x] `destroy` `destroy_n` (#4869)
- [x] `transform_reduce` (#5260)

**Comment by toktarev** [comment]
I will try to start working on `copy_if copy_n`
