### ISSUE TITLE
Create V1.6.1 release

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#5301]
In preparation for a V1.6.1 release, here is a list of PRs that could be backported:

Mandatory:

- [ ] Attempting to fix datapar compilation issues (#5235)

Optional:

- [ ] Fixed source file line statements in examples documentation (#5290)
- [ ] Replacing util::function_nonser on std::function in hpx_init (#5284)
- [ ] Fix typo in docs (#5276)
- [ ] Support annotations in hpx::transform_reduce (#5267)
- [ ] Leverage no_unique_address for member_pack (#5265)
- [ ] Make sure annotations are used in the binary transform (#5238)
- [ ] Sort printed config options (#5231)

More:
- [ ] Allow splitting of futures holding std::tuple (#5289)
- [ ] Fix more GCC 10 deprecation warnings (#5279)
- [ ] Fix bogus deprecation warnings with GCC 10 (#5272)
- [ ] Small fixes and improvements to CUDA/MPI polling (#5277)
- [ ] Correcting target ids for symbol_namespace::iterate (#5271)
- [ ] Making sure late command line options are recognized as configuration options (#5259)
- [ ] Making late command line options available for local runtime (#5266)
- [ ] Another attempt at fixing the Fedora 35 problem (#5194)
- [ ] Force CMake to set the -std=c++XX flag (#5187)
- [ ] Fixing Fedora 35 for Power architectures (#5182)

Removed (doesn't affect users):
- [x] ~Retry CDash submissions on failure (#5273)~

**Comment by hkaiser** [comment]
We decided to directly go for releasing V1.7. Closing now.
