### ISSUE TITLE
Possible V1.7.1 release

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#5486]
Here is a list of PRs that could potentially go into a V1.7.1 release, if needed:

- [x] Adding bound-checking for bind placeholders (#5489)
- [x] Add Asio version check (#5485)
- [x] Change extra archive data to rely on uniqueness of a variable address, not a function address (#5482)
- [x] More fixes to enable for all types to be assumed to be bitwise copyable (#5448)

The following PRs are just nice to haves (they don't 'fix' anything):
- [x] Improve performance of Spinlocks (#5445)
- [x] Adapt transform_inclusive_scan to C++ 20 (#5444)
- [x] Adapt transform_exclusive_scan to C++ 20 (#5440)
- [x] Adapt inclusive_scan to C++ 20 (#5439)
- [x] Adapt exclusive_scan to C++20 (#5436)
