### ISSUE TITLE
HEP: Conformance to C++23

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/hpx#5654]
This is a meta ticket collecting all issues related to conformance with C++23, please edit as needed:

- [x] Add `starts_with` and `ends_with` algorithms (#5381)
- [ ] Implement P2248 for our algorithms (#5653)
- [ ] Implement datapar for parallel algorithms (#2333)

Not exactly C++23, but still important for conformance:

- [ ] Make sure HPX conforms to N4755 (#3364)
