### ISSUE TITLE
Fix S/R versions of the parallel algorithms

### ISSUE THREAD

**Issue by zhekemist** [STEllAR-GROUP/hpx#6535]
PR #6494 adds unit test cases and fixes for the S/R versions of a subset of HPX's parallel algorithms. This issue serves to track the remaining algorithms that have not yet been adapted to work with S/R and/or do not yet have unit test cases for their S/R versions:

- [ ] `copy_if`
- [ ] `exclusive_scan`
- [ ] `for_loop` (see PR #6529)
- [ ] `for_loop_n` (see PR #6529)
- [ ] `for_loop_strided` (see PR #6529)
- [ ] `for_loop_n_strided` (see PR #6529)
- [ ] `inclusive_scan`
- [ ] `make_heap`
- [ ] `merge`
- [ ] `inplace_merge`
- [ ] `nth_element`
- [ ] `partial_sort`
- [ ] `partial_sort_copy`
- [ ] `stable_partition`
- [ ] `partition`
- [ ] `partition_copy`
- [ ] `reduce_by_key`
- [ ] `remove_copy`
- [ ] `remove_copy_if`
- [ ] `search_n`
- [ ] `set_difference`
- [ ] `set_intersection`
- [ ] `set_symmetric_difference`
- [ ] `set_union`
- [ ] `shift_left`
- [ ] `shift_right`
- [ ] `sort`
- [ ] `sort_by_key`
- [ ] `stable_sort`
- [ ] `transform_exclusive_scan`
- [ ] `transform_inclusive_scan`
- [ ] `uninitialized_copy`
- [ ] `uninitialized_copy_n`
- [ ] `uninitialized_default_construct`
- [ ] `uninitialized_default_construct_n`
- [ ] `uninitialized_fill`
- [ ] `unititialized_fill_n`
- [ ] `uninitialized_move`
- [ ] `uninitialized_move_n`
- [ ] `uninitialized_relocate`
- [ ] `uninitialized_relocate_backward`
- [ ] `uninitialized_relocate_n`
- [ ] `uninitialized_value_construct`
- [ ] `uninitialized_value_construct_n`
- [ ] `unique_copy`

Note: During the work on PR #6494, S/R unit tests were added for some algorithms without also fixing their S/R versions. To avoid cluttering the tests, these temporarily non-functional unit test cases were removed. However, if they are needed for future work, you they can be restored by reverting commit [a20f1b4](https://github.com/STEllAR-GROUP/hpx/pull/6494/commits/a20f1b4da8e49de5d4380dd23a5c928525106768).  See [this spreadsheet](https://docs.google.com/spreadsheets/d/1zbz88UZn912nLiBMbRaMTQTU2lT0vZRigui4jrcbIRA/edit?usp=sharing) from the PR for a list of algorithms for which unit test cases were originally added.

**Comment by 360NK** [comment]
I would like to work on adding the S/R unit test for copy_if. Will submit a PR shortly.

**Comment by mooofin** [comment]
@hkaiser hi , id like to help out with adding these , was thinking of starting with remove_copy_if unless someone is already working on it?

**Comment by hkaiser** [comment]
> @hkaiser hi , id like to help out with adding these , was thinking of starting with remove_copy_if unless someone is already working on it?

Please be my guest, even if `remove_copy_if` is a difficult algorithm to start with as the underlying `scan_partitioner` has not been look at from the standpoint of S&R yet.

**Comment by mooofin** [comment]
got it ,  hadn't looked into the `scan_partitioner` yet , i'll go through scan-related S/R internals first then . Thanks

**Comment by mooofin** [comment]
@hkaiser hi , would it be ok if i send a PR for `shift_left `and` shift_right `, since they dont use `scan_partitioner`

**Comment by hkaiser** [comment]
> [@hkaiser](https://github.com/hkaiser) hi , would it be ok if i send a PR for `shift_left `and`shift_right`, since they dont use `scan_partitioner`

Please feel free to do that.

**Comment by udaykiriti** [comment]
@hkaiser hii, can I implement  `set_symmetric_difference`.
